### ISSUE TITLE
Servings network name is hardcoded

### ISSUE THREAD

**Issue by orion-belt** [OPENAIRINTERFACE/ngap-tester#10]
Servings network name is hard-coded with MCC, MNC value.
It will be good if MCC, MNC from config is used.

https://github.com/omec-project/gnbsim/blob/main/realue/handler.go#L27

* For more details
https://github.com/omec-project/gnbsim/issues/68

**Comment by lionelgo** [comment]
In the working branch https://github.com/OPENAIRINTERFACE/gnbsim/blob/donotlookatthis-1/realue/handler.go, this have been removed.

**Comment by orion-belt** [comment]
Verified hence closing this issue.

```bash
[2023-01-24T13:24:25.941994] [AMF] [amf_n1 ] [info ] Received UL_NAS_DATA_IND
[2023-01-24T13:24:25.942064] [AMF] [amf_n1 ] [debug] Serving network name 5G:mnc001.mcc001.3gppnetwork.org
```
